name: Build APK and Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21.0.2'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Prebuild
        run: |
          mv android/ android_temp/
          npx expo prebuild --platform android
          \cp -frT android_temp/ android/
      - name: Install React Native cli
        run: npm i -D @react-native-community/cli
      - name: Build APK
        run: |
          cd android
          ./gradlew app:assembleRelease --no-daemon
          cp app/build/outputs/apk/release/app-release.apk ../airplain.apk
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: airplain.apk
          token: ${{ secrets.RELEASE_TOKEN }}
          body_path: ${{ github.workspace }}/release-notes.txt
          draft: false
          prerelease: false
          make_latest: true
