name: Build APK and Create GitHub Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  build:
    name: Install and build
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21.0.2'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Prebuild
        run: |
          mv android/ android_temp/
          npx expo prebuild --platform android
          \cp -frT android_temp/ android/
          sed -i 's/signingConfig signingConfigs.debug/signingConfig null/g' android/app/build.gradle
      - name: Build APK
        run: |
          cd android
          ./gradlew app:assembleRelease --no-daemon
      - name: Sign APK
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > release.keystore
          $ANDROID_SDK_ROOT/build-tools/36.0.0/apksigner sign \
            --ks release.keystore \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --out airplain.apk \
            android/app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: airplain.apk
          token: ${{ secrets.RELEASE_TOKEN }}
          body_path: ${{ github.workspace }}/release-notes.txt
          draft: false
          prerelease: false
          make_latest: true
