name: Run tests
on:
  pull_request:

  push:
    branches: [main]
    paths:
      - android/**
      - package.json
      - src/**
      - tests/**
      - .github/workflows/test.yml

  workflow_call:

  workflow_dispatch:

jobs:
  run-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          npm ci
      - name: Run Prettier check
        run: |
          npm run prettier:check
      - name: Run Lint check
        run: |
          npm run lint
      - name: Run Jest tests
        run: |
          npm run test
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
      - name: Run Android unit tests
        run: |
          npm run test:android
